#!/usr/bin/env bash
# AgentSearch one-shot installer for Debian / Ubuntu.
#
# Idempotent — safe to re-run after a code update (`git pull` + rerun).
# Drops a hardened systemd unit at /etc/systemd/system/agentsearch.service
# and an environment file at /etc/agentsearch/env (auto-generates a
# bearer token on first run; preserves it on subsequent runs).
#
# Usage (as root):
#   curl -fsSL https://raw.githubusercontent.com/t0ken-ai/AgentSearch/main/deploy/install.sh \
#       | bash
#
# Or after cloning:
#   sudo bash deploy/install.sh
#
# After install, tail logs with:
#   journalctl -u agentsearch -f
# Test locally with:
#   curl -H "Authorization: Bearer $(awk -F= '/^AGENTSEARCH_TOKEN=/{print $2}' /etc/agentsearch/env)" \
#        http://127.0.0.1:8088/health
# Tunnel remotely with:
#   ssh -N -L 8088:127.0.0.1:8088 root@<server>

set -euo pipefail

INSTALL_DIR=${AGENTSEARCH_INSTALL_DIR:-/opt/AgentSearch}
REPO_URL=${AGENTSEARCH_REPO:-https://github.com/t0ken-ai/AgentSearch.git}
SERVICE_USER=${AGENTSEARCH_USER:-agentsearch}
ETC_DIR=/etc/agentsearch
LOG_DIR=/var/log/agentsearch
STATE_DIR=/var/lib/agentsearch

if [ "$(id -u)" -ne 0 ]; then
  echo "error: must run as root (sudo bash $0)" >&2
  exit 1
fi

# ── 1. system deps ─────────────────────────────────────────────────────
echo "==> [1/7] installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -qq -y --no-install-recommends \
    git curl jq openssl ca-certificates \
    python3-venv python3-pip python3-dev build-essential
# CloakBrowser / Chromium runtime libs. Many of these are renamed `libfoo-t64`
# on Ubuntu 24.04+ — try both names so one works on the running release.
for pkg in \
    libnss3 libnspr4 libgbm1 libxkbcommon0 libxcomposite1 libxdamage1 \
    libxfixes3 libxrandr2 libcairo2 libpango-1.0-0 libcups2 libdrm2 \
    libxshmfence1 libxss1 \
    libatk1.0-0 libatk1.0-0t64 libatk-bridge2.0-0 libatk-bridge2.0-0t64 \
    libasound2 libasound2t64
do
  apt-get install -qq -y --no-install-recommends "$pkg" 2>/dev/null || true
done

# ── 2. dedicated user ──────────────────────────────────────────────────
echo "==> [2/7] creating service user '$SERVICE_USER'"
id "$SERVICE_USER" &>/dev/null || \
  useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"

# ── 3. clone or pull ───────────────────────────────────────────────────
echo "==> [3/7] sync code into $INSTALL_DIR"
if [ ! -d "$INSTALL_DIR/.git" ]; then
  git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
else
  git -C "$INSTALL_DIR" fetch --quiet origin
  git -C "$INSTALL_DIR" reset --hard --quiet origin/main
fi
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# ── 4. venv + pip install ──────────────────────────────────────────────
echo "==> [4/7] python venv + pip install"
if [ ! -d "$INSTALL_DIR/venv" ]; then
  python3 -m venv "$INSTALL_DIR/venv"
fi
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"
"$INSTALL_DIR/venv/bin/pip" install --quiet -e "$INSTALL_DIR"
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/venv"

# ── 5. /etc/agentsearch/env ────────────────────────────────────────────
echo "==> [5/7] config dirs + env file"
mkdir -p "$ETC_DIR" "$STATE_DIR" "$LOG_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$STATE_DIR" "$LOG_DIR"
if [ ! -f "$ETC_DIR/env" ] || ! grep -q AGENTSEARCH_TOKEN "$ETC_DIR/env"; then
  TOKEN=$(openssl rand -hex 32)
  cat > "$ETC_DIR/env" <<EOF
# Auto-generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
AGENTSEARCH_TOKEN=$TOKEN
# Uncomment to route through a residential proxy:
# FLUXISP_PROXY=http://USER:PASS@host:port
AGENTSEARCH_LOG=INFO
EOF
  echo "   generated new token; first 8 chars: ${TOKEN:0:8}…"
else
  echo "   $ETC_DIR/env exists, kept (token preserved)"
fi
chown "$SERVICE_USER:$SERVICE_USER" "$ETC_DIR/env"
chmod 600 "$ETC_DIR/env"

# ── 6. systemd unit ────────────────────────────────────────────────────
echo "==> [6/7] systemd unit"
install -m 644 \
    "$INSTALL_DIR/deploy/systemd/agentsearch.service" \
    /etc/systemd/system/agentsearch.service
systemctl daemon-reload
systemctl enable agentsearch.service
# Always restart so a code update via re-running install.sh actually
# loads new Python modules — `enable --now` is a no-op when already running.
systemctl restart agentsearch.service

# ── 7. health probe ────────────────────────────────────────────────────
echo "==> [7/7] waiting for /health…"
for i in $(seq 1 15); do
  if curl -fsS --max-time 2 \
       -H "Authorization: Bearer $(awk -F= '/^AGENTSEARCH_TOKEN=/{print $2}' "$ETC_DIR/env")" \
       http://127.0.0.1:8088/health >/dev/null 2>&1; then
    echo "    up after ${i}s"
    break
  fi
  sleep 1
done

cat <<DONE
==================================================================
  AgentSearch deployed — service active and enabled at boot.

  Status:    systemctl status agentsearch
  Logs:      journalctl -u agentsearch -f
  Token:     awk -F= '/^AGENTSEARCH_TOKEN=/{print \$2}' /etc/agentsearch/env

  Local test:
    curl -H "Authorization: Bearer \$TOKEN" http://127.0.0.1:8088/health

  Remote use (from your laptop):
    ssh -N -L 8088:127.0.0.1:8088 user@<this-server>
    # then on your laptop:
    curl -H "Authorization: Bearer \$TOKEN" http://127.0.0.1:8088/list-engines
==================================================================
DONE
